# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Colt Gainey
title: Software Development Engineer
email: colt.gainey@gmail.com
# email_title: Email (Email title override)
phone: (803) 229-0667
# phone_title: Phone (Phone title override)
website: you're here!
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  ColtG-py
linkedin_username: colt-gainey

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/1632930757696.jfif
about_content: | # this will include new lines to allow paragraphs
  I'm a passionate and driven engineer that specializes in cloud architecture, integrating DevOps practices, and creating/leveraging ML solutions. I've got a proven track record of helping organizations deliver their products to customers faster, more reliably, and more securly through a litany of cloud solutions. I'm always looking for the next big challenge, and constantly studying new best practices.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: BracarAI
        quote: >
          Deep insights into your business data, no matter the size.
        description: | # this will include new lines to allow paragraphs
          Researched and lead development of internal product, BracarAI, which leverages latest LLM advancements to create an application capable of taking large amounts of customer data, vectorizing on demand, and offering a seemless chatting experience with that data.
  
          Fully realized, fully capable multi-tenant application capable of supporting many companies with many different models due to it's on-demand, event driven architecture. 
          
          Full stack app created with the following technologies: Amplify, Lambda, API Gateway, DynamoDB, S3, Cognito, React JS
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Smoke Test Automation
        quote: >
          Automated E2E product testing done 24/7 in all production deployments.
        description: | # this will include new lines to allow paragraphs
          Conceptualized, researched, developed, and rolled out complete end-to-end testing platform which can be used to quickly and easily run any test suite dozens of times per hour, supporting a variety of operating systems and testing frameworks (Cypress, Selenium, Robot).
          
          Services 5 critical products within the Infor ecosystem, providing constant alerting in the event of a degredation or downtime. To date, has caught nearly a dozen outages before the rest of our alerting caught on, reducing MTTD and MTTR.
          
          Runs serverlessly via Docker and Lambda, utilizing GitLab CI as the CICD pipeline of choice along with AWS SAM to deploy Lambda docker containers. Features testing on demand via API Gateway. Forwards metrics off to CloudWatch, where it then utilizes anomaly detection to intelligently detect degredations and downtime.
          
          Features a front-end component written ReactJS which calls the backend API to serve current monitoring results on demand, and also in graphical format. Utilizes our Active Domain through Microsoft to gate access.
      - layout: left
        border: weak
        title: Near-Zero Downtime Upgrade
        quote: >
          Leveraging Blue/Green deployments to reduce customer downtime during updates by 95%.
        description: | # this will include new lines to allow paragraphs
          Worked as part of a small team in charge of drastically reducing the downtime of customers during hotfixes and production updates. Utilized a variety of AWS services (ECS, ApacheMQ, ALB, DynamoDB) to deploy an updated farm, then systematically update each customers database before switching their routing to the new farm.
          
          Resulted in a 95% reduction in the downtime of customers during upgrades, taking what was a 2+ hour process down to a handful of minutes.   
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Bracari
        sub_title: Software Development Engineer
        caption: April 2022 - present
        link: www.bracari.com
        quote: >
          Solve important problems for good reasons.
        description: | # this will include new lines to allow paragraphs
          Lead agile team development of AI product which leveraged latest LLM technology to offer deep insights into customer data.
          Work with exciting new ML technologies to better leverage data we generate, utilizing LLM's, LangChain, Vectorstores, and event driven ETL.
          Broke down monolithic application into dockerized microservice components, improving time to market, elasticity, and recovery.
          Creating a full end to end build, release, deploy, and monitor CI/CD pipeline powered by Github Actions, Maven, AWS, and Sonarqube that allows us to focus on code and solutions, and worry less about the dependability of our deliverables.
          Optimize CI/CD for speed and agility on a per project basis, and integrate developer feedback and needs to better service both development and operations.
          Contribute to full-stack development of flagship application, utilizing TypeScript, React, Next JS, and Java Spring. 
          Developing a variety of API's used throughout applications.
      - layout: right
        title: Infor
        sub_title: Development Operations Engineer
        caption: June 2019 - April 2022
        link: www.infor.com
        quote: >
          Specialized enterprise solutions for complex applications.
        description: | # this will include new lines to allow paragraphs
          Developed DevOps solutions for multiple products which solved a variety of problems from monitoring gaps to toil reduction.
          Heavily utilized and architected solutions in AWS, spanning dozens of services. Utilized Gitlab CI and Jenkins for deployment CI/CD, and Terraform / AWS SAM for IaC.
          Utilized Docker to configure and deploy consistent images and tasks as part of business logic.
          Utilized K9s to configure and manage Kubernetes clusters.
          Led agile team in the development of Smoke Test Automation with duties which included sprint management, blameless post mortems, stand-ups, and retrospectives.
          Assisted with critical production outages and deployments, RCA calls, outage postmortems, and SOP standardization. Collaborated across many different teams to achieve all aforementioned solutions.
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Clemson University
        sub_title: Computer Science
        caption: 2017 - 2020
        quote: >
          Pursed degree in Computer Science. 
        description: | # this will include new lines to allow paragraphs
          Obtained degree featuring course work in Networking, Data Structures and Algorithms, Operating Systems, Human Computer Interactions, and more.
  - title: Skills
    layout: list
    content:
      - layout: top-right
        description: | # this will include new lines to allow paragraphs
          ***Cloud Skills***: AWS (EC2, ECS, EKS, EBS, ALB, Lambda, API Gateway, DynamoDB, SQS, MQ), Azure (Administrative)
          
          ***Containerization***: Docker / Kubernetes
          
          ***CI/CD***: Gitlab CI, Jenkins, AWS CodeDeploy, AWS CodePipeline
          
          ***Infrastructure as Code***: Terraform, AWS SAM, CloudFormation, proprietary tooling
         
          ***Scripting***: Python, ReactJS, TypeScript, Java
          
          ***App Development***: Python, ReactJS, C++
          
          ***Project Management and Leadership***
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I spend my free time pursuing other interests like rock climbing, music, sports science, and history. I'm also the proud owner of a blind cat. He probably knows too much, as I talk him through all of my programming problems.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
